# create external secret: docker secret create aws-credentials $HOME/.aws/credentials
version: '3.9'

secrets:
  aws-credentials:
    external: true

services:
  crawler:
    image: 127.0.0.1:5000/poogle/crawler
    build: .
    container_name: crawler
    environment:
      - TIME_LIMIT=3600
    user: root
    secrets:
      - source: aws-credentials
        target: /root/.aws/credentials
        mode: 0400
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
